<?php
/***********************************************************************
 * *
 *  *
 *  * @copyright Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  * @author    info@boolfly.com
 * *
 */
?>
<script type="text/x-magento-init">
    {
        "[data-role=wishlist-product]": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "ajaxWishlist": {
                        "component": "Boolfly_AjaxWishlist/js/ajaxWishlist"
                    }
                }
            }
        }
    }
</script>